### ISSUE TITLE
Webhook fails to process "record.create" messages

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/pyfulcrum#17]
FulcrumAPP is sending messages to our webhook, but the server is not able to process them.
From the webhook.log file:
```
Cannot process event record.create for id 2888a1b2-3114-481f-b1cf-d7799cfd34b9 in test webhook: Expecting value: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "/home/geosolutions/work/pyfulcrum-dev/repo/pyfulcrum/web/src/pyfulcrum/web/webhooks.py", line 54, in fulcrum_call
    payload)
  File "/home/geosolutions/work/pyfulcrum-dev/repo/pyfulcrum/web/src/pyfulcrum/web/webhooks.py", line 137, in _handle_webhook
    mgr.get(res_id, cached=False)
  File "/home/geosolutions/work/pyfulcrum-dev/repo/pyfulcrum/lib/src/pyfulcrum/lib/api.py", line 60, in get
    data = self._handler.find(obj_id)
  File "/home/geosolutions/work/pyfulcrum-dev/venv/lib64/python3.6/site-packages/fulcrum/mixins.py", line 5, in find
    api_resp = self.client.call('get', '{0}/{1}'.format(self.path, id))
  File "/home/geosolutions/work/pyfulcrum-dev/venv/lib64/python3.6/site-packages/fulcrum/api/__init__.py", line 57, in call
    return resp.json()
  File "/home/geosolutions/work/pyfulcrum-dev/venv/lib64/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```

Example of a JSON payload:
```
{
	"id": "c165570f-8ff0-46e6-8864-8d0664b3dd37",
	"type": "record.create",
	"owner_id": "be4f27d9-59bf-449b-b3ba-398155af93d6",
	"data": {
		"status": null,
		"version": 1,
		"id": "becc2e18-2c6b-418a-9ade-12ec6d4438a7",
		"created_at": "2018-12-09T01:52:14Z",
		"updated_at": "2018-12-09T01:52:14Z",
		"client_created_at": "2018-12-09T01:52:14Z",
		"client_updated_at": "2018-12-09T01:52:14Z",
		"created_by": "John Reinier",
		"created_by_id": "9e85b47f-215a-4a8c-b2ab-6adb8bcaa944",
		"updated_by": "John Reinier",
		"updated_by_id": "9e85b47f-215a-4a8c-b2ab-6adb8bcaa944",
		"created_location": null,
		"updated_location": null,
		"created_duration": null,
		"updated_duration": null,
		"edited_duration": null,
		"history_change_type": "c",
		"form_id": "c41392bc-0eee-4112-8f63-1fcc1b5f2747",
		"form_version": 1,
		"project_id": null,
		"assigned_to": null,
		"assigned_to_id": null,
		"form_values": {
			"62f0": "Agrostis clandestina",
			"e377": "Agrostis clandestina"
		},
		"latitude": null,
		"longitude": null,
		"altitude": null,
		"speed": null,
		"course": null,
		"horizontal_accuracy": null,
		"vertical_accuracy": null,
		"history_id": "c165570f-8ff0-46e6-8864-8d0664b3dd37",
		"history_changed_by_id": "9e85b47f-215a-4a8c-b2ab-6adb8bcaa944",
		"history_changed_by": "John Reinier",
		"history_created_at": "2018-12-09T01:52:14Z"
	}
}
```

**Comment by tdipisa** [comment]
It seems a fulcrum issue: I hace deleted the webhook and then recreated it to fix the problems. Now is working well again.
